2024-10-06 21:37:39,446 INFO    StreamThr :8536 [internal.py:wandb_internal():85] W&B internal server running at pid: 8536, started at: 2024-10-06 21:37:39.446496
2024-10-06 21:37:39,447 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: status
2024-10-06 21:37:39,449 INFO    WriterThread:8536 [datastore.py:open_for_write():87] open: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/run-2xfeuhn9.wandb
2024-10-06 21:37:39,449 DEBUG   SenderThread:8536 [sender.py:send():379] send: header
2024-10-06 21:37:39,450 DEBUG   SenderThread:8536 [sender.py:send():379] send: run
2024-10-06 21:37:39,649 INFO    SenderThread:8536 [dir_watcher.py:__init__():211] watching files in: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files
2024-10-06 21:37:39,649 INFO    SenderThread:8536 [sender.py:_start_run_threads():1188] run started: 2xfeuhn9 with start time 1728268659.447493
2024-10-06 21:37:39,655 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: check_version
2024-10-06 21:37:39,655 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: check_version
2024-10-06 21:37:39,713 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: run_start
2024-10-06 21:37:39,806 DEBUG   HandlerThread:8536 [system_info.py:__init__():26] System info init
2024-10-06 21:37:39,808 DEBUG   HandlerThread:8536 [system_info.py:__init__():41] System info init done
2024-10-06 21:37:39,810 INFO    HandlerThread:8536 [system_monitor.py:start():194] Starting system monitor
2024-10-06 21:37:39,813 INFO    SystemMonitor:8536 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-10-06 21:37:39,815 INFO    HandlerThread:8536 [system_monitor.py:probe():214] Collecting system info
2024-10-06 21:37:39,819 INFO    SystemMonitor:8536 [interfaces.py:start():188] Started cpu monitoring
2024-10-06 21:37:39,828 INFO    SystemMonitor:8536 [interfaces.py:start():188] Started disk monitoring
2024-10-06 21:37:39,829 INFO    SystemMonitor:8536 [interfaces.py:start():188] Started gpuapple monitoring
2024-10-06 21:37:39,830 ERROR   HandlerThread:8536 [gpu_apple.py:probe():176] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:37:39,832 INFO    SystemMonitor:8536 [interfaces.py:start():188] Started memory monitoring
2024-10-06 21:37:39,834 ERROR   gpuapple  :8536 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:37:39,837 DEBUG   HandlerThread:8536 [system_info.py:probe():152] Probing system
2024-10-06 21:37:39,839 INFO    SystemMonitor:8536 [interfaces.py:start():188] Started network monitoring
2024-10-06 21:37:39,843 DEBUG   HandlerThread:8536 [gitlib.py:_init_repo():56] git repository is invalid
2024-10-06 21:37:39,843 DEBUG   HandlerThread:8536 [system_info.py:probe():200] Probing system done
2024-10-06 21:37:39,843 DEBUG   HandlerThread:8536 [system_monitor.py:probe():223] {'os': 'macOS-14.6.1-arm64-arm-64bit', 'python': '3.12.2', 'heartbeatAt': '2024-10-07T02:37:39.838922', 'startedAt': '2024-10-07T02:37:39.440668', 'docker': None, 'cuda': None, 'args': ('data.pkl',), 'state': 'running', 'program': '/Users/milind/Desktop/valence/milind_code/non_llm.py', 'codePathLocal': 'non_llm.py', 'codePath': 'non_llm.py', 'host': 'Milinds-MacBook-Pro.local', 'username': 'milind', 'executable': '/opt/anaconda3/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 166.77970504760742}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-10-06 21:37:39,843 INFO    HandlerThread:8536 [system_monitor.py:probe():224] Finished collecting system info
2024-10-06 21:37:39,843 INFO    HandlerThread:8536 [system_monitor.py:probe():227] Publishing system info
2024-10-06 21:37:39,843 DEBUG   HandlerThread:8536 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-10-06 21:37:40,655 INFO    Thread-12 :8536 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/conda-environment.yaml
2024-10-06 21:37:41,951 ERROR   gpuapple  :8536 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:37:42,376 DEBUG   HandlerThread:8536 [system_info.py:_save_conda():224] Saving conda packages done
2024-10-06 21:37:42,377 INFO    HandlerThread:8536 [system_monitor.py:probe():229] Finished publishing system info
2024-10-06 21:37:42,379 DEBUG   SenderThread:8536 [sender.py:send():379] send: files
2024-10-06 21:37:42,380 INFO    SenderThread:8536 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-10-06 21:37:42,660 INFO    Thread-12 :8536 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/conda-environment.yaml
2024-10-06 21:37:42,660 INFO    Thread-12 :8536 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/wandb-metadata.json
2024-10-06 21:37:42,731 INFO    wandb-upload_0:8536 [upload_job.py:push():130] Uploaded file /var/folders/jv/wvjkll0d0vl_clbchr37hpk40000gn/T/tmpp0wr65nkwandb/lcs7s8lj-wandb-metadata.json
2024-10-06 21:37:42,742 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: python_packages
2024-10-06 21:37:42,742 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: python_packages
2024-10-06 21:37:42,743 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 21:37:42,743 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: stop_status
2024-10-06 21:37:42,744 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:42,804 DEBUG   SenderThread:8536 [sender.py:send():379] send: telemetry
2024-10-06 21:37:43,666 INFO    Thread-12 :8536 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/output.log
2024-10-06 21:37:43,667 INFO    Thread-12 :8536 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/requirements.txt
2024-10-06 21:37:43,750 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:43,964 ERROR   gpuapple  :8536 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:37:44,755 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:44,844 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:37:45,676 INFO    Thread-12 :8536 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/output.log
2024-10-06 21:37:45,754 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:45,980 ERROR   gpuapple  :8536 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:37:46,760 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:47,762 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:48,025 ERROR   gpuapple  :8536 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:37:48,787 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:49,802 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:50,037 ERROR   gpuapple  :8536 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:37:50,792 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:37:50,802 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:51,859 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:52,055 ERROR   gpuapple  :8536 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:37:52,862 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:53,870 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:54,068 ERROR   gpuapple  :8536 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:37:54,888 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:55,891 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:56,090 ERROR   gpuapple  :8536 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:37:56,797 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:37:56,893 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:57,749 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 21:37:57,749 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: stop_status
2024-10-06 21:37:57,899 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:58,097 ERROR   gpuapple  :8536 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:37:58,906 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:59,869 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:37:59,870 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:37:59,870 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:37:59,870 DEBUG   SenderThread:8536 [sender.py:send():379] send: history
2024-10-06 21:37:59,871 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:37:59,871 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:37:59,875 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:37:59,876 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:37:59,877 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:37:59,877 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:37:59,878 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:37:59,879 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:37:59,879 INFO    SenderThread:8536 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:37:59,879 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:37:59,880 DEBUG   SenderThread:8536 [sender.py:send():379] send: history
2024-10-06 21:37:59,880 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:37:59,881 INFO    SenderThread:8536 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:37:59,881 DEBUG   SenderThread:8536 [sender.py:send():379] send: history
2024-10-06 21:37:59,881 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:37:59,881 INFO    SenderThread:8536 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:37:59,881 DEBUG   SenderThread:8536 [sender.py:send():379] send: history
2024-10-06 21:37:59,881 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:37:59,881 INFO    SenderThread:8536 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:37:59,881 DEBUG   SenderThread:8536 [sender.py:send():379] send: history
2024-10-06 21:37:59,881 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:37:59,881 INFO    SenderThread:8536 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:37:59,882 DEBUG   SenderThread:8536 [sender.py:send():379] send: history
2024-10-06 21:37:59,882 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:37:59,882 INFO    SenderThread:8536 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:37:59,882 DEBUG   SenderThread:8536 [sender.py:send():379] send: history
2024-10-06 21:37:59,882 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:37:59,882 INFO    SenderThread:8536 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:37:59,882 DEBUG   SenderThread:8536 [sender.py:send():379] send: history
2024-10-06 21:37:59,882 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:37:59,882 INFO    SenderThread:8536 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:37:59,882 DEBUG   SenderThread:8536 [sender.py:send():379] send: history
2024-10-06 21:37:59,882 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:37:59,882 INFO    SenderThread:8536 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:37:59,882 DEBUG   SenderThread:8536 [sender.py:send():379] send: history
2024-10-06 21:37:59,882 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:37:59,883 INFO    SenderThread:8536 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:37:59,883 DEBUG   SenderThread:8536 [sender.py:send():379] send: history
2024-10-06 21:37:59,883 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:37:59,883 INFO    SenderThread:8536 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:37:59,910 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:37:59,910 INFO    Thread-12 :8536 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/wandb-summary.json
2024-10-06 21:38:00,105 ERROR   gpuapple  :8536 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:38:00,914 INFO    Thread-12 :8536 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/output.log
2024-10-06 21:38:00,936 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:38:01,297 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:38:01,297 DEBUG   SenderThread:8536 [sender.py:send():379] send: history
2024-10-06 21:38:01,297 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:38:01,298 INFO    SenderThread:8536 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:38:01,302 DEBUG   SenderThread:8536 [sender.py:send():379] send: telemetry
2024-10-06 21:38:01,303 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: server_info
2024-10-06 21:38:01,303 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: server_info
2024-10-06 21:38:01,337 DEBUG   SenderThread:8536 [sender.py:send():379] send: exit
2024-10-06 21:38:01,337 INFO    SenderThread:8536 [sender.py:send_exit():586] handling exit code: 0
2024-10-06 21:38:01,338 INFO    SenderThread:8536 [sender.py:send_exit():588] handling runtime: 21
2024-10-06 21:38:01,338 INFO    SenderThread:8536 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:38:01,338 INFO    SenderThread:8536 [sender.py:send_exit():594] send defer
2024-10-06 21:38:01,338 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:38:01,338 INFO    HandlerThread:8536 [handler.py:handle_request_defer():184] handle defer: 0
2024-10-06 21:38:01,338 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: defer
2024-10-06 21:38:01,338 INFO    SenderThread:8536 [sender.py:send_request_defer():610] handle sender defer: 0
2024-10-06 21:38:01,338 INFO    SenderThread:8536 [sender.py:transition_state():614] send defer: 1
2024-10-06 21:38:01,338 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:38:01,338 INFO    HandlerThread:8536 [handler.py:handle_request_defer():184] handle defer: 1
2024-10-06 21:38:01,338 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: defer
2024-10-06 21:38:01,338 INFO    SenderThread:8536 [sender.py:send_request_defer():610] handle sender defer: 1
2024-10-06 21:38:01,338 INFO    SenderThread:8536 [sender.py:transition_state():614] send defer: 2
2024-10-06 21:38:01,338 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:38:01,338 INFO    HandlerThread:8536 [handler.py:handle_request_defer():184] handle defer: 2
2024-10-06 21:38:01,338 INFO    HandlerThread:8536 [system_monitor.py:finish():203] Stopping system monitor
2024-10-06 21:38:01,338 DEBUG   SystemMonitor:8536 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-10-06 21:38:01,338 INFO    HandlerThread:8536 [interfaces.py:finish():200] Joined cpu monitor
2024-10-06 21:38:01,339 DEBUG   SystemMonitor:8536 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-10-06 21:38:01,339 INFO    HandlerThread:8536 [interfaces.py:finish():200] Joined disk monitor
2024-10-06 21:38:01,339 DEBUG   SystemMonitor:8536 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-10-06 21:38:01,339 INFO    HandlerThread:8536 [interfaces.py:finish():200] Joined gpuapple monitor
2024-10-06 21:38:01,339 INFO    HandlerThread:8536 [interfaces.py:finish():200] Joined memory monitor
2024-10-06 21:38:01,339 INFO    HandlerThread:8536 [interfaces.py:finish():200] Joined network monitor
2024-10-06 21:38:01,339 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: defer
2024-10-06 21:38:01,339 INFO    SenderThread:8536 [sender.py:send_request_defer():610] handle sender defer: 2
2024-10-06 21:38:01,339 INFO    SenderThread:8536 [sender.py:transition_state():614] send defer: 3
2024-10-06 21:38:01,339 DEBUG   SenderThread:8536 [sender.py:send():379] send: telemetry
2024-10-06 21:38:01,339 DEBUG   SenderThread:8536 [sender.py:send():379] send: stats
2024-10-06 21:38:01,340 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:38:01,340 INFO    HandlerThread:8536 [handler.py:handle_request_defer():184] handle defer: 3
2024-10-06 21:38:01,340 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: defer
2024-10-06 21:38:01,340 INFO    SenderThread:8536 [sender.py:send_request_defer():610] handle sender defer: 3
2024-10-06 21:38:01,340 INFO    SenderThread:8536 [sender.py:transition_state():614] send defer: 4
2024-10-06 21:38:01,340 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:38:01,340 INFO    HandlerThread:8536 [handler.py:handle_request_defer():184] handle defer: 4
2024-10-06 21:38:01,340 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: defer
2024-10-06 21:38:01,340 INFO    SenderThread:8536 [sender.py:send_request_defer():610] handle sender defer: 4
2024-10-06 21:38:01,340 INFO    SenderThread:8536 [sender.py:transition_state():614] send defer: 5
2024-10-06 21:38:01,340 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:38:01,340 INFO    HandlerThread:8536 [handler.py:handle_request_defer():184] handle defer: 5
2024-10-06 21:38:01,340 DEBUG   SenderThread:8536 [sender.py:send():379] send: summary
2024-10-06 21:38:01,340 INFO    SenderThread:8536 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:38:01,340 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: defer
2024-10-06 21:38:01,340 INFO    SenderThread:8536 [sender.py:send_request_defer():610] handle sender defer: 5
2024-10-06 21:38:01,340 INFO    SenderThread:8536 [sender.py:transition_state():614] send defer: 6
2024-10-06 21:38:01,340 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:38:01,340 INFO    HandlerThread:8536 [handler.py:handle_request_defer():184] handle defer: 6
2024-10-06 21:38:01,340 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: defer
2024-10-06 21:38:01,340 INFO    SenderThread:8536 [sender.py:send_request_defer():610] handle sender defer: 6
2024-10-06 21:38:01,342 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:38:01,442 INFO    SenderThread:8536 [sender.py:transition_state():614] send defer: 7
2024-10-06 21:38:01,442 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:38:01,442 INFO    HandlerThread:8536 [handler.py:handle_request_defer():184] handle defer: 7
2024-10-06 21:38:01,442 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: defer
2024-10-06 21:38:01,442 INFO    SenderThread:8536 [sender.py:send_request_defer():610] handle sender defer: 7
2024-10-06 21:38:01,920 INFO    Thread-12 :8536 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/wandb-summary.json
2024-10-06 21:38:01,921 INFO    Thread-12 :8536 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/config.yaml
2024-10-06 21:38:02,340 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:38:02,874 INFO    SenderThread:8536 [sender.py:transition_state():614] send defer: 8
2024-10-06 21:38:02,875 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:38:02,875 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:38:02,876 INFO    HandlerThread:8536 [handler.py:handle_request_defer():184] handle defer: 8
2024-10-06 21:38:02,876 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: defer
2024-10-06 21:38:02,876 INFO    SenderThread:8536 [sender.py:send_request_defer():610] handle sender defer: 8
2024-10-06 21:38:02,876 INFO    SenderThread:8536 [job_builder.py:build():440] Attempting to build job artifact
2024-10-06 21:38:02,878 INFO    SenderThread:8536 [job_builder.py:_get_source_type():580] no source found
2024-10-06 21:38:02,878 INFO    SenderThread:8536 [sender.py:transition_state():614] send defer: 9
2024-10-06 21:38:02,878 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:38:02,878 INFO    HandlerThread:8536 [handler.py:handle_request_defer():184] handle defer: 9
2024-10-06 21:38:02,879 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: defer
2024-10-06 21:38:02,879 INFO    SenderThread:8536 [sender.py:send_request_defer():610] handle sender defer: 9
2024-10-06 21:38:02,879 INFO    SenderThread:8536 [dir_watcher.py:finish():358] shutting down directory watcher
2024-10-06 21:38:02,922 INFO    SenderThread:8536 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/output.log
2024-10-06 21:38:02,922 INFO    SenderThread:8536 [dir_watcher.py:finish():388] scan: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files
2024-10-06 21:38:02,923 INFO    SenderThread:8536 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/requirements.txt requirements.txt
2024-10-06 21:38:02,923 INFO    SenderThread:8536 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/output.log output.log
2024-10-06 21:38:02,923 INFO    SenderThread:8536 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/config.yaml config.yaml
2024-10-06 21:38:02,925 INFO    SenderThread:8536 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/wandb-summary.json wandb-summary.json
2024-10-06 21:38:02,926 INFO    SenderThread:8536 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/conda-environment.yaml conda-environment.yaml
2024-10-06 21:38:02,926 INFO    SenderThread:8536 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/wandb-metadata.json wandb-metadata.json
2024-10-06 21:38:02,927 INFO    SenderThread:8536 [sender.py:transition_state():614] send defer: 10
2024-10-06 21:38:02,927 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:38:02,927 INFO    HandlerThread:8536 [handler.py:handle_request_defer():184] handle defer: 10
2024-10-06 21:38:02,930 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: defer
2024-10-06 21:38:02,931 INFO    SenderThread:8536 [sender.py:send_request_defer():610] handle sender defer: 10
2024-10-06 21:38:02,932 INFO    SenderThread:8536 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:38:03,117 INFO    wandb-upload_0:8536 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/requirements.txt
2024-10-06 21:38:03,163 INFO    wandb-upload_1:8536 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/output.log
2024-10-06 21:38:03,164 INFO    wandb-upload_2:8536 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/config.yaml
2024-10-06 21:38:03,177 INFO    wandb-upload_3:8536 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/wandb-summary.json
2024-10-06 21:38:03,208 INFO    wandb-upload_4:8536 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/files/conda-environment.yaml
2024-10-06 21:38:03,348 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:38:03,349 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:38:03,414 INFO    Thread-11 (_thread_body):8536 [sender.py:transition_state():614] send defer: 11
2024-10-06 21:38:03,416 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:38:03,416 INFO    HandlerThread:8536 [handler.py:handle_request_defer():184] handle defer: 11
2024-10-06 21:38:03,417 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: defer
2024-10-06 21:38:03,417 INFO    SenderThread:8536 [sender.py:send_request_defer():610] handle sender defer: 11
2024-10-06 21:38:03,417 INFO    SenderThread:8536 [file_pusher.py:join():175] waiting for file pusher
2024-10-06 21:38:03,417 INFO    SenderThread:8536 [sender.py:transition_state():614] send defer: 12
2024-10-06 21:38:03,418 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:38:03,418 INFO    HandlerThread:8536 [handler.py:handle_request_defer():184] handle defer: 12
2024-10-06 21:38:03,418 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: defer
2024-10-06 21:38:03,418 INFO    SenderThread:8536 [sender.py:send_request_defer():610] handle sender defer: 12
2024-10-06 21:38:03,419 INFO    SenderThread:8536 [file_stream.py:finish():601] file stream finish called
2024-10-06 21:38:03,505 INFO    SenderThread:8536 [file_stream.py:finish():605] file stream finish is done
2024-10-06 21:38:03,505 INFO    SenderThread:8536 [sender.py:transition_state():614] send defer: 13
2024-10-06 21:38:03,506 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:38:03,506 INFO    HandlerThread:8536 [handler.py:handle_request_defer():184] handle defer: 13
2024-10-06 21:38:03,506 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: defer
2024-10-06 21:38:03,506 INFO    SenderThread:8536 [sender.py:send_request_defer():610] handle sender defer: 13
2024-10-06 21:38:03,506 INFO    SenderThread:8536 [sender.py:transition_state():614] send defer: 14
2024-10-06 21:38:03,507 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:38:03,507 DEBUG   SenderThread:8536 [sender.py:send():379] send: final
2024-10-06 21:38:03,507 INFO    HandlerThread:8536 [handler.py:handle_request_defer():184] handle defer: 14
2024-10-06 21:38:03,507 DEBUG   SenderThread:8536 [sender.py:send():379] send: footer
2024-10-06 21:38:03,507 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: defer
2024-10-06 21:38:03,507 INFO    SenderThread:8536 [sender.py:send_request_defer():610] handle sender defer: 14
2024-10-06 21:38:03,508 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:38:03,508 DEBUG   SenderThread:8536 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:38:03,509 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:38:03,510 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: get_summary
2024-10-06 21:38:03,510 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: sampled_history
2024-10-06 21:38:03,517 DEBUG   HandlerThread:8536 [handler.py:handle_request():158] handle_request: shutdown
2024-10-06 21:38:03,517 INFO    HandlerThread:8536 [handler.py:finish():882] shutting down handler
2024-10-06 21:38:04,517 INFO    WriterThread:8536 [datastore.py:close():296] close: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213739-2xfeuhn9/run-2xfeuhn9.wandb
2024-10-06 21:38:04,519 INFO    SenderThread:8536 [sender.py:finish():1608] shutting down sender
2024-10-06 21:38:04,519 INFO    SenderThread:8536 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:38:04,520 INFO    SenderThread:8536 [file_pusher.py:join():175] waiting for file pusher
