2024-10-06 23:14:29,877 INFO    StreamThr :10110 [internal.py:wandb_internal():85] W&B internal server running at pid: 10110, started at: 2024-10-06 23:14:29.876483
2024-10-06 23:14:29,878 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: status
2024-10-06 23:14:29,879 INFO    WriterThread:10110 [datastore.py:open_for_write():87] open: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/run-bqtty7me.wandb
2024-10-06 23:14:29,882 DEBUG   SenderThread:10110 [sender.py:send():379] send: header
2024-10-06 23:14:29,882 DEBUG   SenderThread:10110 [sender.py:send():379] send: run
2024-10-06 23:14:30,796 INFO    SenderThread:10110 [dir_watcher.py:__init__():211] watching files in: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files
2024-10-06 23:14:30,796 INFO    SenderThread:10110 [sender.py:_start_run_threads():1188] run started: bqtty7me with start time 1728274469.877316
2024-10-06 23:14:30,802 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: check_version
2024-10-06 23:14:30,802 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: check_version
2024-10-06 23:14:30,860 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: run_start
2024-10-06 23:14:30,867 DEBUG   HandlerThread:10110 [system_info.py:__init__():26] System info init
2024-10-06 23:14:30,867 DEBUG   HandlerThread:10110 [system_info.py:__init__():41] System info init done
2024-10-06 23:14:30,867 INFO    HandlerThread:10110 [system_monitor.py:start():194] Starting system monitor
2024-10-06 23:14:30,868 INFO    SystemMonitor:10110 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-10-06 23:14:30,868 INFO    HandlerThread:10110 [system_monitor.py:probe():214] Collecting system info
2024-10-06 23:14:30,870 INFO    SystemMonitor:10110 [interfaces.py:start():188] Started cpu monitoring
2024-10-06 23:14:30,872 ERROR   HandlerThread:10110 [gpu_apple.py:probe():176] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 23:14:30,872 INFO    SystemMonitor:10110 [interfaces.py:start():188] Started disk monitoring
2024-10-06 23:14:30,875 DEBUG   HandlerThread:10110 [system_info.py:probe():152] Probing system
2024-10-06 23:14:30,875 INFO    SystemMonitor:10110 [interfaces.py:start():188] Started gpuapple monitoring
2024-10-06 23:14:30,877 INFO    SystemMonitor:10110 [interfaces.py:start():188] Started memory monitoring
2024-10-06 23:14:30,878 ERROR   gpuapple  :10110 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 23:14:30,878 INFO    SystemMonitor:10110 [interfaces.py:start():188] Started network monitoring
2024-10-06 23:14:30,880 DEBUG   HandlerThread:10110 [gitlib.py:_init_repo():56] git repository is invalid
2024-10-06 23:14:30,880 DEBUG   HandlerThread:10110 [system_info.py:probe():200] Probing system done
2024-10-06 23:14:30,880 DEBUG   HandlerThread:10110 [system_monitor.py:probe():223] {'os': 'macOS-14.6.1-arm64-arm-64bit', 'python': '3.12.2', 'heartbeatAt': '2024-10-07T04:14:30.875270', 'startedAt': '2024-10-07T04:14:29.862991', 'docker': None, 'cuda': None, 'args': ('data.pkl', 'XGB'), 'state': 'running', 'program': '/Users/milind/Desktop/valence/milind_code/train_non_llm.py', 'codePathLocal': 'train_non_llm.py', 'codePath': 'train_non_llm.py', 'host': 'Milinds-MacBook-Pro.local', 'username': 'milind', 'executable': '/opt/anaconda3/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 165.37332153320312}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-10-06 23:14:30,880 INFO    HandlerThread:10110 [system_monitor.py:probe():224] Finished collecting system info
2024-10-06 23:14:30,880 INFO    HandlerThread:10110 [system_monitor.py:probe():227] Publishing system info
2024-10-06 23:14:30,880 DEBUG   HandlerThread:10110 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-10-06 23:14:31,802 INFO    Thread-12 :10110 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/conda-environment.yaml
2024-10-06 23:14:32,885 ERROR   gpuapple  :10110 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 23:14:32,936 DEBUG   HandlerThread:10110 [system_info.py:_save_conda():224] Saving conda packages done
2024-10-06 23:14:32,936 INFO    HandlerThread:10110 [system_monitor.py:probe():229] Finished publishing system info
2024-10-06 23:14:32,938 DEBUG   SenderThread:10110 [sender.py:send():379] send: files
2024-10-06 23:14:32,938 INFO    SenderThread:10110 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-10-06 23:14:33,169 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: python_packages
2024-10-06 23:14:33,169 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: python_packages
2024-10-06 23:14:33,170 DEBUG   SenderThread:10110 [sender.py:send():379] send: telemetry
2024-10-06 23:14:33,170 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 23:14:33,170 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 23:14:33,170 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: stop_status
2024-10-06 23:14:33,376 INFO    wandb-upload_0:10110 [upload_job.py:push():130] Uploaded file /var/folders/jv/wvjkll0d0vl_clbchr37hpk40000gn/T/tmpz7itsb7wwandb/lc30gpb6-wandb-metadata.json
2024-10-06 23:14:33,811 INFO    Thread-12 :10110 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/conda-environment.yaml
2024-10-06 23:14:33,812 INFO    Thread-12 :10110 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/requirements.txt
2024-10-06 23:14:33,812 INFO    Thread-12 :10110 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/wandb-metadata.json
2024-10-06 23:14:34,174 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 23:14:34,935 ERROR   gpuapple  :10110 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 23:14:35,177 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 23:14:35,349 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 23:14:36,180 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 23:14:36,951 ERROR   gpuapple  :10110 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 23:14:37,186 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 23:14:38,190 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 23:14:38,959 ERROR   gpuapple  :10110 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 23:14:39,195 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 23:14:40,200 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 23:14:40,969 ERROR   gpuapple  :10110 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 23:14:41,192 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 23:14:41,205 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 23:14:42,210 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 23:14:42,977 ERROR   gpuapple  :10110 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 23:14:43,215 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 23:14:44,261 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 23:14:44,607 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 23:14:44,608 DEBUG   SenderThread:10110 [sender.py:send():379] send: history
2024-10-06 23:14:44,608 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: summary_record
2024-10-06 23:14:44,609 INFO    SenderThread:10110 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 23:14:44,610 DEBUG   SenderThread:10110 [sender.py:send():379] send: telemetry
2024-10-06 23:14:44,611 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: server_info
2024-10-06 23:14:44,611 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: server_info
2024-10-06 23:14:44,771 DEBUG   SenderThread:10110 [sender.py:send():379] send: exit
2024-10-06 23:14:44,771 INFO    SenderThread:10110 [sender.py:send_exit():586] handling exit code: 0
2024-10-06 23:14:44,772 INFO    SenderThread:10110 [sender.py:send_exit():588] handling runtime: 13
2024-10-06 23:14:44,772 INFO    SenderThread:10110 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 23:14:44,772 INFO    SenderThread:10110 [sender.py:send_exit():594] send defer
2024-10-06 23:14:44,772 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: defer
2024-10-06 23:14:44,773 INFO    HandlerThread:10110 [handler.py:handle_request_defer():184] handle defer: 0
2024-10-06 23:14:44,773 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: defer
2024-10-06 23:14:44,773 INFO    SenderThread:10110 [sender.py:send_request_defer():610] handle sender defer: 0
2024-10-06 23:14:44,773 INFO    SenderThread:10110 [sender.py:transition_state():614] send defer: 1
2024-10-06 23:14:44,773 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: defer
2024-10-06 23:14:44,773 INFO    HandlerThread:10110 [handler.py:handle_request_defer():184] handle defer: 1
2024-10-06 23:14:44,773 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: defer
2024-10-06 23:14:44,773 INFO    SenderThread:10110 [sender.py:send_request_defer():610] handle sender defer: 1
2024-10-06 23:14:44,773 INFO    SenderThread:10110 [sender.py:transition_state():614] send defer: 2
2024-10-06 23:14:44,773 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: defer
2024-10-06 23:14:44,773 INFO    HandlerThread:10110 [handler.py:handle_request_defer():184] handle defer: 2
2024-10-06 23:14:44,773 INFO    HandlerThread:10110 [system_monitor.py:finish():203] Stopping system monitor
2024-10-06 23:14:44,773 DEBUG   SystemMonitor:10110 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-10-06 23:14:44,773 DEBUG   SystemMonitor:10110 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-10-06 23:14:44,773 DEBUG   SystemMonitor:10110 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-10-06 23:14:44,774 INFO    HandlerThread:10110 [interfaces.py:finish():200] Joined cpu monitor
2024-10-06 23:14:44,774 INFO    HandlerThread:10110 [interfaces.py:finish():200] Joined disk monitor
2024-10-06 23:14:44,774 INFO    HandlerThread:10110 [interfaces.py:finish():200] Joined gpuapple monitor
2024-10-06 23:14:44,774 INFO    HandlerThread:10110 [interfaces.py:finish():200] Joined memory monitor
2024-10-06 23:14:44,774 INFO    HandlerThread:10110 [interfaces.py:finish():200] Joined network monitor
2024-10-06 23:14:44,774 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: defer
2024-10-06 23:14:44,774 INFO    SenderThread:10110 [sender.py:send_request_defer():610] handle sender defer: 2
2024-10-06 23:14:44,774 INFO    SenderThread:10110 [sender.py:transition_state():614] send defer: 3
2024-10-06 23:14:44,774 DEBUG   SenderThread:10110 [sender.py:send():379] send: telemetry
2024-10-06 23:14:44,775 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: defer
2024-10-06 23:14:44,775 INFO    HandlerThread:10110 [handler.py:handle_request_defer():184] handle defer: 3
2024-10-06 23:14:44,775 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: defer
2024-10-06 23:14:44,775 INFO    SenderThread:10110 [sender.py:send_request_defer():610] handle sender defer: 3
2024-10-06 23:14:44,775 INFO    SenderThread:10110 [sender.py:transition_state():614] send defer: 4
2024-10-06 23:14:44,775 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: defer
2024-10-06 23:14:44,775 INFO    HandlerThread:10110 [handler.py:handle_request_defer():184] handle defer: 4
2024-10-06 23:14:44,775 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: defer
2024-10-06 23:14:44,775 INFO    SenderThread:10110 [sender.py:send_request_defer():610] handle sender defer: 4
2024-10-06 23:14:44,775 INFO    SenderThread:10110 [sender.py:transition_state():614] send defer: 5
2024-10-06 23:14:44,775 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: defer
2024-10-06 23:14:44,775 INFO    HandlerThread:10110 [handler.py:handle_request_defer():184] handle defer: 5
2024-10-06 23:14:44,775 DEBUG   SenderThread:10110 [sender.py:send():379] send: summary
2024-10-06 23:14:44,776 INFO    SenderThread:10110 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 23:14:44,776 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: defer
2024-10-06 23:14:44,776 INFO    SenderThread:10110 [sender.py:send_request_defer():610] handle sender defer: 5
2024-10-06 23:14:44,776 INFO    SenderThread:10110 [sender.py:transition_state():614] send defer: 6
2024-10-06 23:14:44,776 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: defer
2024-10-06 23:14:44,776 INFO    HandlerThread:10110 [handler.py:handle_request_defer():184] handle defer: 6
2024-10-06 23:14:44,776 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: defer
2024-10-06 23:14:44,776 INFO    SenderThread:10110 [sender.py:send_request_defer():610] handle sender defer: 6
2024-10-06 23:14:44,779 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 23:14:44,873 INFO    SenderThread:10110 [sender.py:transition_state():614] send defer: 7
2024-10-06 23:14:44,873 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: defer
2024-10-06 23:14:44,873 INFO    HandlerThread:10110 [handler.py:handle_request_defer():184] handle defer: 7
2024-10-06 23:14:44,873 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: defer
2024-10-06 23:14:44,874 INFO    SenderThread:10110 [sender.py:send_request_defer():610] handle sender defer: 7
2024-10-06 23:14:44,892 INFO    Thread-12 :10110 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/config.yaml
2024-10-06 23:14:44,892 INFO    Thread-12 :10110 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/wandb-summary.json
2024-10-06 23:14:44,892 INFO    Thread-12 :10110 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/output.log
2024-10-06 23:14:45,774 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 23:14:46,616 INFO    SenderThread:10110 [sender.py:transition_state():614] send defer: 8
2024-10-06 23:14:46,617 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 23:14:46,617 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: defer
2024-10-06 23:14:46,618 INFO    HandlerThread:10110 [handler.py:handle_request_defer():184] handle defer: 8
2024-10-06 23:14:46,618 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: defer
2024-10-06 23:14:46,618 INFO    SenderThread:10110 [sender.py:send_request_defer():610] handle sender defer: 8
2024-10-06 23:14:46,618 INFO    SenderThread:10110 [job_builder.py:build():440] Attempting to build job artifact
2024-10-06 23:14:46,620 INFO    SenderThread:10110 [job_builder.py:_get_source_type():580] no source found
2024-10-06 23:14:46,620 INFO    SenderThread:10110 [sender.py:transition_state():614] send defer: 9
2024-10-06 23:14:46,620 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: defer
2024-10-06 23:14:46,620 INFO    HandlerThread:10110 [handler.py:handle_request_defer():184] handle defer: 9
2024-10-06 23:14:46,621 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: defer
2024-10-06 23:14:46,621 INFO    SenderThread:10110 [sender.py:send_request_defer():610] handle sender defer: 9
2024-10-06 23:14:46,621 INFO    SenderThread:10110 [dir_watcher.py:finish():358] shutting down directory watcher
2024-10-06 23:14:46,779 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 23:14:46,898 INFO    SenderThread:10110 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/output.log
2024-10-06 23:14:46,899 INFO    SenderThread:10110 [dir_watcher.py:finish():388] scan: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files
2024-10-06 23:14:46,899 INFO    SenderThread:10110 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/requirements.txt requirements.txt
2024-10-06 23:14:46,899 INFO    SenderThread:10110 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/output.log output.log
2024-10-06 23:14:46,899 INFO    SenderThread:10110 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/config.yaml config.yaml
2024-10-06 23:14:46,902 INFO    SenderThread:10110 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/wandb-summary.json wandb-summary.json
2024-10-06 23:14:46,904 INFO    SenderThread:10110 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/conda-environment.yaml conda-environment.yaml
2024-10-06 23:14:46,905 INFO    SenderThread:10110 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/wandb-metadata.json wandb-metadata.json
2024-10-06 23:14:46,906 INFO    SenderThread:10110 [sender.py:transition_state():614] send defer: 10
2024-10-06 23:14:46,906 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 23:14:46,908 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: defer
2024-10-06 23:14:46,910 INFO    HandlerThread:10110 [handler.py:handle_request_defer():184] handle defer: 10
2024-10-06 23:14:46,911 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: defer
2024-10-06 23:14:46,911 INFO    SenderThread:10110 [sender.py:send_request_defer():610] handle sender defer: 10
2024-10-06 23:14:46,912 INFO    SenderThread:10110 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 23:14:47,117 INFO    wandb-upload_1:10110 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/output.log
2024-10-06 23:14:47,129 INFO    wandb-upload_2:10110 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/config.yaml
2024-10-06 23:14:47,175 INFO    wandb-upload_4:10110 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/conda-environment.yaml
2024-10-06 23:14:47,188 INFO    wandb-upload_3:10110 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/wandb-summary.json
2024-10-06 23:14:47,189 INFO    wandb-upload_0:10110 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/files/requirements.txt
2024-10-06 23:14:47,391 INFO    Thread-11 (_thread_body):10110 [sender.py:transition_state():614] send defer: 11
2024-10-06 23:14:47,392 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: defer
2024-10-06 23:14:47,392 INFO    HandlerThread:10110 [handler.py:handle_request_defer():184] handle defer: 11
2024-10-06 23:14:47,393 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: defer
2024-10-06 23:14:47,393 INFO    SenderThread:10110 [sender.py:send_request_defer():610] handle sender defer: 11
2024-10-06 23:14:47,393 INFO    SenderThread:10110 [file_pusher.py:join():175] waiting for file pusher
2024-10-06 23:14:47,395 INFO    SenderThread:10110 [sender.py:transition_state():614] send defer: 12
2024-10-06 23:14:47,396 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: defer
2024-10-06 23:14:47,396 INFO    HandlerThread:10110 [handler.py:handle_request_defer():184] handle defer: 12
2024-10-06 23:14:47,396 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: defer
2024-10-06 23:14:47,396 INFO    SenderThread:10110 [sender.py:send_request_defer():610] handle sender defer: 12
2024-10-06 23:14:47,396 INFO    SenderThread:10110 [file_stream.py:finish():601] file stream finish called
2024-10-06 23:14:47,484 INFO    SenderThread:10110 [file_stream.py:finish():605] file stream finish is done
2024-10-06 23:14:47,484 INFO    SenderThread:10110 [sender.py:transition_state():614] send defer: 13
2024-10-06 23:14:47,484 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: defer
2024-10-06 23:14:47,485 INFO    HandlerThread:10110 [handler.py:handle_request_defer():184] handle defer: 13
2024-10-06 23:14:47,485 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: defer
2024-10-06 23:14:47,485 INFO    SenderThread:10110 [sender.py:send_request_defer():610] handle sender defer: 13
2024-10-06 23:14:47,485 INFO    SenderThread:10110 [sender.py:transition_state():614] send defer: 14
2024-10-06 23:14:47,485 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: defer
2024-10-06 23:14:47,486 DEBUG   SenderThread:10110 [sender.py:send():379] send: final
2024-10-06 23:14:47,486 INFO    HandlerThread:10110 [handler.py:handle_request_defer():184] handle defer: 14
2024-10-06 23:14:47,486 DEBUG   SenderThread:10110 [sender.py:send():379] send: footer
2024-10-06 23:14:47,486 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: defer
2024-10-06 23:14:47,486 INFO    SenderThread:10110 [sender.py:send_request_defer():610] handle sender defer: 14
2024-10-06 23:14:47,487 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 23:14:47,488 DEBUG   SenderThread:10110 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 23:14:47,489 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 23:14:47,490 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: get_summary
2024-10-06 23:14:47,490 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: sampled_history
2024-10-06 23:14:47,491 DEBUG   HandlerThread:10110 [handler.py:handle_request():158] handle_request: shutdown
2024-10-06 23:14:47,491 INFO    HandlerThread:10110 [handler.py:finish():882] shutting down handler
2024-10-06 23:14:48,493 INFO    SenderThread:10110 [sender.py:finish():1608] shutting down sender
2024-10-06 23:14:48,493 INFO    WriterThread:10110 [datastore.py:close():296] close: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_231429-bqtty7me/run-bqtty7me.wandb
2024-10-06 23:14:48,494 INFO    SenderThread:10110 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 23:14:48,494 INFO    SenderThread:10110 [file_pusher.py:join():175] waiting for file pusher
