2024-10-06 21:21:51,492 INFO    StreamThr :7849 [internal.py:wandb_internal():85] W&B internal server running at pid: 7849, started at: 2024-10-06 21:21:51.491607
2024-10-06 21:21:51,493 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: status
2024-10-06 21:21:51,494 INFO    WriterThread:7849 [datastore.py:open_for_write():87] open: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/run-guapux2b.wandb
2024-10-06 21:21:51,495 DEBUG   SenderThread:7849 [sender.py:send():379] send: header
2024-10-06 21:21:51,495 DEBUG   SenderThread:7849 [sender.py:send():379] send: run
2024-10-06 21:21:51,683 INFO    SenderThread:7849 [dir_watcher.py:__init__():211] watching files in: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files
2024-10-06 21:21:51,683 INFO    SenderThread:7849 [sender.py:_start_run_threads():1188] run started: guapux2b with start time 1728267711.492155
2024-10-06 21:21:51,689 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: check_version
2024-10-06 21:21:51,689 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: check_version
2024-10-06 21:21:51,746 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: run_start
2024-10-06 21:21:51,753 DEBUG   HandlerThread:7849 [system_info.py:__init__():26] System info init
2024-10-06 21:21:51,753 DEBUG   HandlerThread:7849 [system_info.py:__init__():41] System info init done
2024-10-06 21:21:51,753 INFO    HandlerThread:7849 [system_monitor.py:start():194] Starting system monitor
2024-10-06 21:21:51,753 INFO    SystemMonitor:7849 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-10-06 21:21:51,753 INFO    HandlerThread:7849 [system_monitor.py:probe():214] Collecting system info
2024-10-06 21:21:51,756 INFO    SystemMonitor:7849 [interfaces.py:start():188] Started cpu monitoring
2024-10-06 21:21:51,758 ERROR   HandlerThread:7849 [gpu_apple.py:probe():176] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:21:51,758 INFO    SystemMonitor:7849 [interfaces.py:start():188] Started disk monitoring
2024-10-06 21:21:51,760 DEBUG   HandlerThread:7849 [system_info.py:probe():152] Probing system
2024-10-06 21:21:51,761 INFO    SystemMonitor:7849 [interfaces.py:start():188] Started gpuapple monitoring
2024-10-06 21:21:51,762 INFO    SystemMonitor:7849 [interfaces.py:start():188] Started memory monitoring
2024-10-06 21:21:51,763 ERROR   gpuapple  :7849 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:21:51,763 INFO    SystemMonitor:7849 [interfaces.py:start():188] Started network monitoring
2024-10-06 21:21:51,766 DEBUG   HandlerThread:7849 [gitlib.py:_init_repo():56] git repository is invalid
2024-10-06 21:21:51,766 DEBUG   HandlerThread:7849 [system_info.py:probe():200] Probing system done
2024-10-06 21:21:51,766 DEBUG   HandlerThread:7849 [system_monitor.py:probe():223] {'os': 'macOS-14.6.1-arm64-arm-64bit', 'python': '3.12.2', 'heartbeatAt': '2024-10-07T02:21:51.761049', 'startedAt': '2024-10-07T02:21:51.486561', 'docker': None, 'cuda': None, 'args': ('data.pkl',), 'state': 'running', 'program': '/Users/milind/Desktop/valence/milind_code/non_llm.py', 'codePathLocal': 'non_llm.py', 'codePath': 'non_llm.py', 'host': 'Milinds-MacBook-Pro.local', 'username': 'milind', 'executable': '/opt/anaconda3/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 166.4197883605957}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-10-06 21:21:51,766 INFO    HandlerThread:7849 [system_monitor.py:probe():224] Finished collecting system info
2024-10-06 21:21:51,766 INFO    HandlerThread:7849 [system_monitor.py:probe():227] Publishing system info
2024-10-06 21:21:51,766 DEBUG   HandlerThread:7849 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-10-06 21:21:52,689 INFO    Thread-12 :7849 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/conda-environment.yaml
2024-10-06 21:21:53,770 ERROR   gpuapple  :7849 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:21:53,924 DEBUG   HandlerThread:7849 [system_info.py:_save_conda():224] Saving conda packages done
2024-10-06 21:21:53,925 INFO    HandlerThread:7849 [system_monitor.py:probe():229] Finished publishing system info
2024-10-06 21:21:53,927 DEBUG   SenderThread:7849 [sender.py:send():379] send: files
2024-10-06 21:21:53,927 INFO    SenderThread:7849 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-10-06 21:21:54,163 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: python_packages
2024-10-06 21:21:54,164 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: python_packages
2024-10-06 21:21:54,164 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 21:21:54,164 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: stop_status
2024-10-06 21:21:54,165 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:21:54,221 DEBUG   SenderThread:7849 [sender.py:send():379] send: telemetry
2024-10-06 21:21:54,258 INFO    wandb-upload_0:7849 [upload_job.py:push():130] Uploaded file /var/folders/jv/wvjkll0d0vl_clbchr37hpk40000gn/T/tmpbcozhk5ywandb/eo4yo60a-wandb-metadata.json
2024-10-06 21:21:54,699 INFO    Thread-12 :7849 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/conda-environment.yaml
2024-10-06 21:21:54,699 INFO    Thread-12 :7849 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/wandb-metadata.json
2024-10-06 21:21:54,699 INFO    Thread-12 :7849 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/requirements.txt
2024-10-06 21:21:55,170 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:21:55,704 INFO    Thread-12 :7849 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/output.log
2024-10-06 21:21:55,781 ERROR   gpuapple  :7849 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:21:56,178 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:21:56,775 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:21:57,199 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:21:57,713 INFO    Thread-12 :7849 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/output.log
2024-10-06 21:21:57,795 ERROR   gpuapple  :7849 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:21:58,207 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:21:59,211 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:21:59,807 ERROR   gpuapple  :7849 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:22:00,222 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:22:01,220 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:22:01,826 ERROR   gpuapple  :7849 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:22:02,208 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:22:02,224 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:22:03,234 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:22:03,834 ERROR   gpuapple  :7849 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:22:04,240 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:22:05,252 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:22:05,838 ERROR   gpuapple  :7849 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:22:06,252 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:22:07,222 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:22:07,257 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:22:07,845 ERROR   gpuapple  :7849 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:22:08,259 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:22:09,165 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 21:22:09,166 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: stop_status
2024-10-06 21:22:09,264 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:22:09,773 INFO    Thread-12 :7849 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/output.log
2024-10-06 21:22:09,802 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:22:09,802 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:22:09,802 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:22:09,803 DEBUG   SenderThread:7849 [sender.py:send():379] send: history
2024-10-06 21:22:09,803 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:22:09,803 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:22:09,803 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:22:09,803 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:22:09,803 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:22:09,803 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:22:09,803 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:22:09,804 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:22:09,804 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:22:09,805 INFO    SenderThread:7849 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:22:09,805 DEBUG   SenderThread:7849 [sender.py:send():379] send: history
2024-10-06 21:22:09,805 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:22:09,805 INFO    SenderThread:7849 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:22:09,805 DEBUG   SenderThread:7849 [sender.py:send():379] send: history
2024-10-06 21:22:09,805 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:22:09,805 INFO    SenderThread:7849 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:22:09,805 DEBUG   SenderThread:7849 [sender.py:send():379] send: history
2024-10-06 21:22:09,806 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:22:09,806 INFO    SenderThread:7849 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:22:09,806 DEBUG   SenderThread:7849 [sender.py:send():379] send: history
2024-10-06 21:22:09,806 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:22:09,806 INFO    SenderThread:7849 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:22:09,806 DEBUG   SenderThread:7849 [sender.py:send():379] send: history
2024-10-06 21:22:09,806 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:22:09,806 INFO    SenderThread:7849 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:22:09,806 DEBUG   SenderThread:7849 [sender.py:send():379] send: history
2024-10-06 21:22:09,806 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:22:09,806 INFO    SenderThread:7849 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:22:09,806 DEBUG   SenderThread:7849 [sender.py:send():379] send: history
2024-10-06 21:22:09,806 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:22:09,806 INFO    SenderThread:7849 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:22:09,806 DEBUG   SenderThread:7849 [sender.py:send():379] send: history
2024-10-06 21:22:09,806 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:22:09,807 INFO    SenderThread:7849 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:22:09,807 DEBUG   SenderThread:7849 [sender.py:send():379] send: history
2024-10-06 21:22:09,807 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:22:09,807 INFO    SenderThread:7849 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:22:09,807 DEBUG   SenderThread:7849 [sender.py:send():379] send: history
2024-10-06 21:22:09,807 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:22:09,807 INFO    SenderThread:7849 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:22:09,853 ERROR   gpuapple  :7849 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:22:10,267 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:22:10,778 INFO    Thread-12 :7849 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/wandb-summary.json
2024-10-06 21:22:11,267 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:22:11,783 INFO    Thread-12 :7849 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/output.log
2024-10-06 21:22:11,860 ERROR   gpuapple  :7849 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:22:12,294 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:22:12,370 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:22:12,373 DEBUG   SenderThread:7849 [sender.py:send():379] send: telemetry
2024-10-06 21:22:12,374 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: server_info
2024-10-06 21:22:12,374 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: server_info
2024-10-06 21:22:12,421 DEBUG   SenderThread:7849 [sender.py:send():379] send: exit
2024-10-06 21:22:12,421 INFO    SenderThread:7849 [sender.py:send_exit():586] handling exit code: 0
2024-10-06 21:22:12,421 INFO    SenderThread:7849 [sender.py:send_exit():588] handling runtime: 20
2024-10-06 21:22:12,421 INFO    SenderThread:7849 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:22:12,422 INFO    SenderThread:7849 [sender.py:send_exit():594] send defer
2024-10-06 21:22:12,422 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:22:12,422 INFO    HandlerThread:7849 [handler.py:handle_request_defer():184] handle defer: 0
2024-10-06 21:22:12,422 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: defer
2024-10-06 21:22:12,422 INFO    SenderThread:7849 [sender.py:send_request_defer():610] handle sender defer: 0
2024-10-06 21:22:12,422 INFO    SenderThread:7849 [sender.py:transition_state():614] send defer: 1
2024-10-06 21:22:12,422 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:22:12,422 INFO    HandlerThread:7849 [handler.py:handle_request_defer():184] handle defer: 1
2024-10-06 21:22:12,422 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: defer
2024-10-06 21:22:12,422 INFO    SenderThread:7849 [sender.py:send_request_defer():610] handle sender defer: 1
2024-10-06 21:22:12,422 INFO    SenderThread:7849 [sender.py:transition_state():614] send defer: 2
2024-10-06 21:22:12,422 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:22:12,422 INFO    HandlerThread:7849 [handler.py:handle_request_defer():184] handle defer: 2
2024-10-06 21:22:12,422 INFO    HandlerThread:7849 [system_monitor.py:finish():203] Stopping system monitor
2024-10-06 21:22:12,422 DEBUG   SystemMonitor:7849 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-10-06 21:22:12,422 INFO    HandlerThread:7849 [interfaces.py:finish():200] Joined cpu monitor
2024-10-06 21:22:12,422 DEBUG   SystemMonitor:7849 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-10-06 21:22:12,422 INFO    HandlerThread:7849 [interfaces.py:finish():200] Joined disk monitor
2024-10-06 21:22:12,423 DEBUG   SystemMonitor:7849 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-10-06 21:22:12,423 INFO    HandlerThread:7849 [interfaces.py:finish():200] Joined gpuapple monitor
2024-10-06 21:22:12,423 INFO    HandlerThread:7849 [interfaces.py:finish():200] Joined memory monitor
2024-10-06 21:22:12,423 INFO    HandlerThread:7849 [interfaces.py:finish():200] Joined network monitor
2024-10-06 21:22:12,423 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: defer
2024-10-06 21:22:12,423 INFO    SenderThread:7849 [sender.py:send_request_defer():610] handle sender defer: 2
2024-10-06 21:22:12,423 INFO    SenderThread:7849 [sender.py:transition_state():614] send defer: 3
2024-10-06 21:22:12,423 DEBUG   SenderThread:7849 [sender.py:send():379] send: telemetry
2024-10-06 21:22:12,423 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:22:12,423 DEBUG   SenderThread:7849 [sender.py:send():379] send: stats
2024-10-06 21:22:12,423 INFO    HandlerThread:7849 [handler.py:handle_request_defer():184] handle defer: 3
2024-10-06 21:22:12,424 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: defer
2024-10-06 21:22:12,424 INFO    SenderThread:7849 [sender.py:send_request_defer():610] handle sender defer: 3
2024-10-06 21:22:12,424 INFO    SenderThread:7849 [sender.py:transition_state():614] send defer: 4
2024-10-06 21:22:12,424 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:22:12,424 INFO    HandlerThread:7849 [handler.py:handle_request_defer():184] handle defer: 4
2024-10-06 21:22:12,424 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: defer
2024-10-06 21:22:12,424 INFO    SenderThread:7849 [sender.py:send_request_defer():610] handle sender defer: 4
2024-10-06 21:22:12,424 INFO    SenderThread:7849 [sender.py:transition_state():614] send defer: 5
2024-10-06 21:22:12,424 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:22:12,424 INFO    HandlerThread:7849 [handler.py:handle_request_defer():184] handle defer: 5
2024-10-06 21:22:12,424 DEBUG   SenderThread:7849 [sender.py:send():379] send: summary
2024-10-06 21:22:12,424 INFO    SenderThread:7849 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:22:12,424 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: defer
2024-10-06 21:22:12,424 INFO    SenderThread:7849 [sender.py:send_request_defer():610] handle sender defer: 5
2024-10-06 21:22:12,424 INFO    SenderThread:7849 [sender.py:transition_state():614] send defer: 6
2024-10-06 21:22:12,424 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:22:12,424 INFO    HandlerThread:7849 [handler.py:handle_request_defer():184] handle defer: 6
2024-10-06 21:22:12,424 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: defer
2024-10-06 21:22:12,424 INFO    SenderThread:7849 [sender.py:send_request_defer():610] handle sender defer: 6
2024-10-06 21:22:12,426 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:22:12,514 INFO    SenderThread:7849 [sender.py:transition_state():614] send defer: 7
2024-10-06 21:22:12,514 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:22:12,514 INFO    HandlerThread:7849 [handler.py:handle_request_defer():184] handle defer: 7
2024-10-06 21:22:12,514 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: defer
2024-10-06 21:22:12,514 INFO    SenderThread:7849 [sender.py:send_request_defer():610] handle sender defer: 7
2024-10-06 21:22:12,790 INFO    Thread-12 :7849 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/wandb-summary.json
2024-10-06 21:22:12,790 INFO    Thread-12 :7849 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/config.yaml
2024-10-06 21:22:13,425 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:22:13,767 INFO    SenderThread:7849 [sender.py:transition_state():614] send defer: 8
2024-10-06 21:22:13,767 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:22:13,768 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:22:13,768 INFO    HandlerThread:7849 [handler.py:handle_request_defer():184] handle defer: 8
2024-10-06 21:22:13,768 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: defer
2024-10-06 21:22:13,769 INFO    SenderThread:7849 [sender.py:send_request_defer():610] handle sender defer: 8
2024-10-06 21:22:13,769 INFO    SenderThread:7849 [job_builder.py:build():440] Attempting to build job artifact
2024-10-06 21:22:13,769 INFO    SenderThread:7849 [job_builder.py:_get_source_type():580] no source found
2024-10-06 21:22:13,769 INFO    SenderThread:7849 [sender.py:transition_state():614] send defer: 9
2024-10-06 21:22:13,770 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:22:13,770 INFO    HandlerThread:7849 [handler.py:handle_request_defer():184] handle defer: 9
2024-10-06 21:22:13,770 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: defer
2024-10-06 21:22:13,770 INFO    SenderThread:7849 [sender.py:send_request_defer():610] handle sender defer: 9
2024-10-06 21:22:13,770 INFO    SenderThread:7849 [dir_watcher.py:finish():358] shutting down directory watcher
2024-10-06 21:22:13,795 INFO    SenderThread:7849 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/output.log
2024-10-06 21:22:13,796 INFO    SenderThread:7849 [dir_watcher.py:finish():388] scan: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files
2024-10-06 21:22:13,797 INFO    SenderThread:7849 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/requirements.txt requirements.txt
2024-10-06 21:22:13,797 INFO    SenderThread:7849 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/output.log output.log
2024-10-06 21:22:13,799 INFO    SenderThread:7849 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/config.yaml config.yaml
2024-10-06 21:22:13,801 INFO    SenderThread:7849 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/wandb-summary.json wandb-summary.json
2024-10-06 21:22:13,802 INFO    SenderThread:7849 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/conda-environment.yaml conda-environment.yaml
2024-10-06 21:22:13,803 INFO    SenderThread:7849 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/wandb-metadata.json wandb-metadata.json
2024-10-06 21:22:13,803 INFO    SenderThread:7849 [sender.py:transition_state():614] send defer: 10
2024-10-06 21:22:13,804 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:22:13,804 INFO    HandlerThread:7849 [handler.py:handle_request_defer():184] handle defer: 10
2024-10-06 21:22:13,806 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: defer
2024-10-06 21:22:13,806 INFO    SenderThread:7849 [sender.py:send_request_defer():610] handle sender defer: 10
2024-10-06 21:22:13,807 INFO    SenderThread:7849 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:22:13,989 INFO    wandb-upload_0:7849 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/requirements.txt
2024-10-06 21:22:14,045 INFO    wandb-upload_3:7849 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/wandb-summary.json
2024-10-06 21:22:14,045 INFO    wandb-upload_1:7849 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/output.log
2024-10-06 21:22:14,096 INFO    wandb-upload_4:7849 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/conda-environment.yaml
2024-10-06 21:22:14,096 INFO    wandb-upload_2:7849 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/files/config.yaml
2024-10-06 21:22:14,300 INFO    Thread-11 (_thread_body):7849 [sender.py:transition_state():614] send defer: 11
2024-10-06 21:22:14,300 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:22:14,300 INFO    HandlerThread:7849 [handler.py:handle_request_defer():184] handle defer: 11
2024-10-06 21:22:14,301 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: defer
2024-10-06 21:22:14,301 INFO    SenderThread:7849 [sender.py:send_request_defer():610] handle sender defer: 11
2024-10-06 21:22:14,301 INFO    SenderThread:7849 [file_pusher.py:join():175] waiting for file pusher
2024-10-06 21:22:14,301 INFO    SenderThread:7849 [sender.py:transition_state():614] send defer: 12
2024-10-06 21:22:14,301 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:22:14,302 INFO    HandlerThread:7849 [handler.py:handle_request_defer():184] handle defer: 12
2024-10-06 21:22:14,302 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: defer
2024-10-06 21:22:14,302 INFO    SenderThread:7849 [sender.py:send_request_defer():610] handle sender defer: 12
2024-10-06 21:22:14,302 INFO    SenderThread:7849 [file_stream.py:finish():601] file stream finish called
2024-10-06 21:22:14,433 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:22:14,603 INFO    SenderThread:7849 [file_stream.py:finish():605] file stream finish is done
2024-10-06 21:22:14,603 INFO    SenderThread:7849 [sender.py:transition_state():614] send defer: 13
2024-10-06 21:22:14,603 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:22:14,604 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:22:14,604 INFO    HandlerThread:7849 [handler.py:handle_request_defer():184] handle defer: 13
2024-10-06 21:22:14,604 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: defer
2024-10-06 21:22:14,605 INFO    SenderThread:7849 [sender.py:send_request_defer():610] handle sender defer: 13
2024-10-06 21:22:14,605 INFO    SenderThread:7849 [sender.py:transition_state():614] send defer: 14
2024-10-06 21:22:14,605 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:22:14,605 DEBUG   SenderThread:7849 [sender.py:send():379] send: final
2024-10-06 21:22:14,605 INFO    HandlerThread:7849 [handler.py:handle_request_defer():184] handle defer: 14
2024-10-06 21:22:14,605 DEBUG   SenderThread:7849 [sender.py:send():379] send: footer
2024-10-06 21:22:14,605 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: defer
2024-10-06 21:22:14,606 INFO    SenderThread:7849 [sender.py:send_request_defer():610] handle sender defer: 14
2024-10-06 21:22:14,606 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:22:14,607 DEBUG   SenderThread:7849 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:22:14,607 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:22:14,608 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: get_summary
2024-10-06 21:22:14,608 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: sampled_history
2024-10-06 21:22:14,611 DEBUG   HandlerThread:7849 [handler.py:handle_request():158] handle_request: shutdown
2024-10-06 21:22:14,611 INFO    HandlerThread:7849 [handler.py:finish():882] shutting down handler
2024-10-06 21:22:15,612 INFO    WriterThread:7849 [datastore.py:close():296] close: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212151-guapux2b/run-guapux2b.wandb
2024-10-06 21:22:15,612 INFO    SenderThread:7849 [sender.py:finish():1608] shutting down sender
2024-10-06 21:22:15,613 INFO    SenderThread:7849 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:22:15,613 INFO    SenderThread:7849 [file_pusher.py:join():175] waiting for file pusher
