2024-10-06 21:26:28,557 INFO    StreamThr :8173 [internal.py:wandb_internal():85] W&B internal server running at pid: 8173, started at: 2024-10-06 21:26:28.556911
2024-10-06 21:26:28,557 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: status
2024-10-06 21:26:28,558 INFO    WriterThread:8173 [datastore.py:open_for_write():87] open: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/run-m7n8eg77.wandb
2024-10-06 21:26:28,559 DEBUG   SenderThread:8173 [sender.py:send():379] send: header
2024-10-06 21:26:28,559 DEBUG   SenderThread:8173 [sender.py:send():379] send: run
2024-10-06 21:26:28,764 INFO    SenderThread:8173 [dir_watcher.py:__init__():211] watching files in: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files
2024-10-06 21:26:28,764 INFO    SenderThread:8173 [sender.py:_start_run_threads():1188] run started: m7n8eg77 with start time 1728267988.557042
2024-10-06 21:26:28,772 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: check_version
2024-10-06 21:26:28,772 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: check_version
2024-10-06 21:26:28,833 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: run_start
2024-10-06 21:26:28,841 DEBUG   HandlerThread:8173 [system_info.py:__init__():26] System info init
2024-10-06 21:26:28,841 DEBUG   HandlerThread:8173 [system_info.py:__init__():41] System info init done
2024-10-06 21:26:28,841 INFO    HandlerThread:8173 [system_monitor.py:start():194] Starting system monitor
2024-10-06 21:26:28,841 INFO    SystemMonitor:8173 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-10-06 21:26:28,841 INFO    HandlerThread:8173 [system_monitor.py:probe():214] Collecting system info
2024-10-06 21:26:28,842 INFO    SystemMonitor:8173 [interfaces.py:start():188] Started cpu monitoring
2024-10-06 21:26:28,847 ERROR   HandlerThread:8173 [gpu_apple.py:probe():176] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:28,848 INFO    SystemMonitor:8173 [interfaces.py:start():188] Started disk monitoring
2024-10-06 21:26:28,850 DEBUG   HandlerThread:8173 [system_info.py:probe():152] Probing system
2024-10-06 21:26:28,852 INFO    SystemMonitor:8173 [interfaces.py:start():188] Started gpuapple monitoring
2024-10-06 21:26:28,854 ERROR   gpuapple  :8173 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:28,854 INFO    SystemMonitor:8173 [interfaces.py:start():188] Started memory monitoring
2024-10-06 21:26:28,855 INFO    SystemMonitor:8173 [interfaces.py:start():188] Started network monitoring
2024-10-06 21:26:28,858 DEBUG   HandlerThread:8173 [gitlib.py:_init_repo():56] git repository is invalid
2024-10-06 21:26:28,858 DEBUG   HandlerThread:8173 [system_info.py:probe():200] Probing system done
2024-10-06 21:26:28,858 DEBUG   HandlerThread:8173 [system_monitor.py:probe():223] {'os': 'macOS-14.6.1-arm64-arm-64bit', 'python': '3.12.2', 'heartbeatAt': '2024-10-07T02:26:28.850636', 'startedAt': '2024-10-07T02:26:28.553849', 'docker': None, 'cuda': None, 'args': ('data.pkl',), 'state': 'running', 'program': '/Users/milind/Desktop/valence/milind_code/non_llm.py', 'codePathLocal': 'non_llm.py', 'codePath': 'non_llm.py', 'host': 'Milinds-MacBook-Pro.local', 'username': 'milind', 'executable': '/opt/anaconda3/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 166.44243240356445}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-10-06 21:26:28,858 INFO    HandlerThread:8173 [system_monitor.py:probe():224] Finished collecting system info
2024-10-06 21:26:28,858 INFO    HandlerThread:8173 [system_monitor.py:probe():227] Publishing system info
2024-10-06 21:26:28,858 DEBUG   HandlerThread:8173 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-10-06 21:26:29,770 INFO    Thread-12 :8173 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/conda-environment.yaml
2024-10-06 21:26:30,862 ERROR   gpuapple  :8173 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:31,041 DEBUG   HandlerThread:8173 [system_info.py:_save_conda():224] Saving conda packages done
2024-10-06 21:26:31,042 INFO    HandlerThread:8173 [system_monitor.py:probe():229] Finished publishing system info
2024-10-06 21:26:31,045 DEBUG   SenderThread:8173 [sender.py:send():379] send: files
2024-10-06 21:26:31,045 INFO    SenderThread:8173 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-10-06 21:26:31,295 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: python_packages
2024-10-06 21:26:31,295 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: python_packages
2024-10-06 21:26:31,297 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 21:26:31,297 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: stop_status
2024-10-06 21:26:31,297 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:31,373 INFO    wandb-upload_0:8173 [upload_job.py:push():130] Uploaded file /var/folders/jv/wvjkll0d0vl_clbchr37hpk40000gn/T/tmp3tcpgqlzwandb/avavjqb8-wandb-metadata.json
2024-10-06 21:26:31,411 DEBUG   SenderThread:8173 [sender.py:send():379] send: telemetry
2024-10-06 21:26:31,779 INFO    Thread-12 :8173 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/conda-environment.yaml
2024-10-06 21:26:31,781 INFO    Thread-12 :8173 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/wandb-metadata.json
2024-10-06 21:26:31,789 INFO    Thread-12 :8173 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/requirements.txt
2024-10-06 21:26:32,320 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:32,810 INFO    Thread-12 :8173 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/output.log
2024-10-06 21:26:32,895 ERROR   gpuapple  :8173 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:33,323 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:34,324 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:34,528 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:26:34,812 INFO    Thread-12 :8173 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/output.log
2024-10-06 21:26:34,916 ERROR   gpuapple  :8173 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:35,328 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:36,355 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:36,924 ERROR   gpuapple  :8173 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:37,359 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:38,375 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:38,931 ERROR   gpuapple  :8173 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:39,375 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:40,322 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:26:40,409 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:40,958 ERROR   gpuapple  :8173 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:41,401 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:42,417 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:42,967 ERROR   gpuapple  :8173 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:43,413 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:44,420 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:44,983 ERROR   gpuapple  :8173 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:45,339 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:26:45,420 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:46,300 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 21:26:46,302 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: stop_status
2024-10-06 21:26:46,421 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:47,011 ERROR   gpuapple  :8173 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:47,422 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:48,429 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:49,019 ERROR   gpuapple  :8173 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:49,427 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:49,879 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:49,880 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:49,880 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:49,881 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:49,881 DEBUG   SenderThread:8173 [sender.py:send():379] send: history
2024-10-06 21:26:49,881 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:49,881 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:49,882 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:49,882 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:49,882 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:49,883 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:49,883 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:49,883 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:49,883 INFO    SenderThread:8173 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:49,884 DEBUG   SenderThread:8173 [sender.py:send():379] send: history
2024-10-06 21:26:49,884 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:49,884 INFO    SenderThread:8173 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:49,884 DEBUG   SenderThread:8173 [sender.py:send():379] send: history
2024-10-06 21:26:49,884 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:49,884 INFO    SenderThread:8173 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:49,884 DEBUG   SenderThread:8173 [sender.py:send():379] send: history
2024-10-06 21:26:49,884 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:49,884 INFO    SenderThread:8173 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:49,885 DEBUG   SenderThread:8173 [sender.py:send():379] send: history
2024-10-06 21:26:49,885 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:49,885 INFO    SenderThread:8173 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:49,885 DEBUG   SenderThread:8173 [sender.py:send():379] send: history
2024-10-06 21:26:49,885 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:49,885 INFO    SenderThread:8173 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:49,885 DEBUG   SenderThread:8173 [sender.py:send():379] send: history
2024-10-06 21:26:49,885 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:49,885 INFO    SenderThread:8173 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:49,885 DEBUG   SenderThread:8173 [sender.py:send():379] send: history
2024-10-06 21:26:49,885 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:49,885 INFO    SenderThread:8173 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:49,885 DEBUG   SenderThread:8173 [sender.py:send():379] send: history
2024-10-06 21:26:49,885 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:49,886 INFO    SenderThread:8173 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:49,886 DEBUG   SenderThread:8173 [sender.py:send():379] send: history
2024-10-06 21:26:49,886 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:49,886 INFO    SenderThread:8173 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:49,886 DEBUG   SenderThread:8173 [sender.py:send():379] send: history
2024-10-06 21:26:49,886 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:49,886 INFO    SenderThread:8173 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:49,902 INFO    Thread-12 :8173 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/wandb-summary.json
2024-10-06 21:26:50,432 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:50,892 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:26:50,907 INFO    Thread-12 :8173 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/output.log
2024-10-06 21:26:51,026 ERROR   gpuapple  :8173 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:51,193 DEBUG   SenderThread:8173 [sender.py:send():379] send: telemetry
2024-10-06 21:26:51,194 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: server_info
2024-10-06 21:26:51,194 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: server_info
2024-10-06 21:26:51,243 DEBUG   SenderThread:8173 [sender.py:send():379] send: exit
2024-10-06 21:26:51,243 INFO    SenderThread:8173 [sender.py:send_exit():586] handling exit code: 0
2024-10-06 21:26:51,243 INFO    SenderThread:8173 [sender.py:send_exit():588] handling runtime: 22
2024-10-06 21:26:51,243 INFO    SenderThread:8173 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:51,243 INFO    SenderThread:8173 [sender.py:send_exit():594] send defer
2024-10-06 21:26:51,244 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:51,244 INFO    HandlerThread:8173 [handler.py:handle_request_defer():184] handle defer: 0
2024-10-06 21:26:51,244 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:51,244 INFO    SenderThread:8173 [sender.py:send_request_defer():610] handle sender defer: 0
2024-10-06 21:26:51,244 INFO    SenderThread:8173 [sender.py:transition_state():614] send defer: 1
2024-10-06 21:26:51,244 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:51,244 INFO    HandlerThread:8173 [handler.py:handle_request_defer():184] handle defer: 1
2024-10-06 21:26:51,244 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:51,244 INFO    SenderThread:8173 [sender.py:send_request_defer():610] handle sender defer: 1
2024-10-06 21:26:51,244 INFO    SenderThread:8173 [sender.py:transition_state():614] send defer: 2
2024-10-06 21:26:51,244 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:51,244 INFO    HandlerThread:8173 [handler.py:handle_request_defer():184] handle defer: 2
2024-10-06 21:26:51,244 INFO    HandlerThread:8173 [system_monitor.py:finish():203] Stopping system monitor
2024-10-06 21:26:51,244 DEBUG   SystemMonitor:8173 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-10-06 21:26:51,244 DEBUG   SystemMonitor:8173 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-10-06 21:26:51,244 DEBUG   SystemMonitor:8173 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-10-06 21:26:51,244 INFO    HandlerThread:8173 [interfaces.py:finish():200] Joined cpu monitor
2024-10-06 21:26:51,244 INFO    HandlerThread:8173 [interfaces.py:finish():200] Joined disk monitor
2024-10-06 21:26:51,244 INFO    HandlerThread:8173 [interfaces.py:finish():200] Joined gpuapple monitor
2024-10-06 21:26:51,244 INFO    HandlerThread:8173 [interfaces.py:finish():200] Joined memory monitor
2024-10-06 21:26:51,245 INFO    HandlerThread:8173 [interfaces.py:finish():200] Joined network monitor
2024-10-06 21:26:51,245 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:51,245 INFO    SenderThread:8173 [sender.py:send_request_defer():610] handle sender defer: 2
2024-10-06 21:26:51,245 INFO    SenderThread:8173 [sender.py:transition_state():614] send defer: 3
2024-10-06 21:26:51,245 DEBUG   SenderThread:8173 [sender.py:send():379] send: telemetry
2024-10-06 21:26:51,245 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:51,245 INFO    HandlerThread:8173 [handler.py:handle_request_defer():184] handle defer: 3
2024-10-06 21:26:51,245 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:51,245 INFO    SenderThread:8173 [sender.py:send_request_defer():610] handle sender defer: 3
2024-10-06 21:26:51,245 INFO    SenderThread:8173 [sender.py:transition_state():614] send defer: 4
2024-10-06 21:26:51,245 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:51,245 INFO    HandlerThread:8173 [handler.py:handle_request_defer():184] handle defer: 4
2024-10-06 21:26:51,245 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:51,245 INFO    SenderThread:8173 [sender.py:send_request_defer():610] handle sender defer: 4
2024-10-06 21:26:51,245 INFO    SenderThread:8173 [sender.py:transition_state():614] send defer: 5
2024-10-06 21:26:51,245 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:51,245 INFO    HandlerThread:8173 [handler.py:handle_request_defer():184] handle defer: 5
2024-10-06 21:26:51,245 DEBUG   SenderThread:8173 [sender.py:send():379] send: summary
2024-10-06 21:26:51,245 INFO    SenderThread:8173 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:51,245 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:51,245 INFO    SenderThread:8173 [sender.py:send_request_defer():610] handle sender defer: 5
2024-10-06 21:26:51,245 INFO    SenderThread:8173 [sender.py:transition_state():614] send defer: 6
2024-10-06 21:26:51,245 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:51,245 INFO    HandlerThread:8173 [handler.py:handle_request_defer():184] handle defer: 6
2024-10-06 21:26:51,245 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:51,245 INFO    SenderThread:8173 [sender.py:send_request_defer():610] handle sender defer: 6
2024-10-06 21:26:51,247 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:26:51,354 INFO    SenderThread:8173 [sender.py:transition_state():614] send defer: 7
2024-10-06 21:26:51,354 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:51,354 INFO    HandlerThread:8173 [handler.py:handle_request_defer():184] handle defer: 7
2024-10-06 21:26:51,354 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:51,354 INFO    SenderThread:8173 [sender.py:send_request_defer():610] handle sender defer: 7
2024-10-06 21:26:51,913 INFO    Thread-12 :8173 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/wandb-summary.json
2024-10-06 21:26:51,914 INFO    Thread-12 :8173 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/config.yaml
2024-10-06 21:26:52,249 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:26:52,575 INFO    SenderThread:8173 [sender.py:transition_state():614] send defer: 8
2024-10-06 21:26:52,575 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:26:52,576 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:52,576 INFO    HandlerThread:8173 [handler.py:handle_request_defer():184] handle defer: 8
2024-10-06 21:26:52,576 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:52,576 INFO    SenderThread:8173 [sender.py:send_request_defer():610] handle sender defer: 8
2024-10-06 21:26:52,576 INFO    SenderThread:8173 [job_builder.py:build():440] Attempting to build job artifact
2024-10-06 21:26:52,578 INFO    SenderThread:8173 [job_builder.py:_get_source_type():580] no source found
2024-10-06 21:26:52,578 INFO    SenderThread:8173 [sender.py:transition_state():614] send defer: 9
2024-10-06 21:26:52,579 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:52,579 INFO    HandlerThread:8173 [handler.py:handle_request_defer():184] handle defer: 9
2024-10-06 21:26:52,579 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:52,579 INFO    SenderThread:8173 [sender.py:send_request_defer():610] handle sender defer: 9
2024-10-06 21:26:52,579 INFO    SenderThread:8173 [dir_watcher.py:finish():358] shutting down directory watcher
2024-10-06 21:26:52,916 INFO    Thread-12 :8173 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/output.log
2024-10-06 21:26:52,916 INFO    SenderThread:8173 [dir_watcher.py:finish():388] scan: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files
2024-10-06 21:26:52,916 INFO    SenderThread:8173 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/requirements.txt requirements.txt
2024-10-06 21:26:52,916 INFO    SenderThread:8173 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/output.log output.log
2024-10-06 21:26:52,917 INFO    SenderThread:8173 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/config.yaml config.yaml
2024-10-06 21:26:52,918 INFO    SenderThread:8173 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/wandb-summary.json wandb-summary.json
2024-10-06 21:26:52,920 INFO    SenderThread:8173 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/conda-environment.yaml conda-environment.yaml
2024-10-06 21:26:52,920 INFO    SenderThread:8173 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/wandb-metadata.json wandb-metadata.json
2024-10-06 21:26:52,920 INFO    SenderThread:8173 [sender.py:transition_state():614] send defer: 10
2024-10-06 21:26:52,921 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:52,922 INFO    HandlerThread:8173 [handler.py:handle_request_defer():184] handle defer: 10
2024-10-06 21:26:52,922 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:52,922 INFO    SenderThread:8173 [sender.py:send_request_defer():610] handle sender defer: 10
2024-10-06 21:26:52,922 INFO    SenderThread:8173 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:26:53,107 INFO    wandb-upload_0:8173 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/requirements.txt
2024-10-06 21:26:53,171 INFO    wandb-upload_3:8173 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/wandb-summary.json
2024-10-06 21:26:53,171 INFO    wandb-upload_4:8173 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/conda-environment.yaml
2024-10-06 21:26:53,171 INFO    wandb-upload_1:8173 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/output.log
2024-10-06 21:26:53,172 INFO    wandb-upload_2:8173 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/files/config.yaml
2024-10-06 21:26:53,251 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:26:53,252 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:26:53,378 INFO    Thread-11 (_thread_body):8173 [sender.py:transition_state():614] send defer: 11
2024-10-06 21:26:53,378 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:53,379 INFO    HandlerThread:8173 [handler.py:handle_request_defer():184] handle defer: 11
2024-10-06 21:26:53,379 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:53,379 INFO    SenderThread:8173 [sender.py:send_request_defer():610] handle sender defer: 11
2024-10-06 21:26:53,379 INFO    SenderThread:8173 [file_pusher.py:join():175] waiting for file pusher
2024-10-06 21:26:53,380 INFO    SenderThread:8173 [sender.py:transition_state():614] send defer: 12
2024-10-06 21:26:53,381 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:53,381 INFO    HandlerThread:8173 [handler.py:handle_request_defer():184] handle defer: 12
2024-10-06 21:26:53,381 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:53,381 INFO    SenderThread:8173 [sender.py:send_request_defer():610] handle sender defer: 12
2024-10-06 21:26:53,381 INFO    SenderThread:8173 [file_stream.py:finish():601] file stream finish called
2024-10-06 21:26:53,475 INFO    SenderThread:8173 [file_stream.py:finish():605] file stream finish is done
2024-10-06 21:26:53,476 INFO    SenderThread:8173 [sender.py:transition_state():614] send defer: 13
2024-10-06 21:26:53,476 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:53,476 INFO    HandlerThread:8173 [handler.py:handle_request_defer():184] handle defer: 13
2024-10-06 21:26:53,476 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:53,477 INFO    SenderThread:8173 [sender.py:send_request_defer():610] handle sender defer: 13
2024-10-06 21:26:53,477 INFO    SenderThread:8173 [sender.py:transition_state():614] send defer: 14
2024-10-06 21:26:53,477 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:53,477 DEBUG   SenderThread:8173 [sender.py:send():379] send: final
2024-10-06 21:26:53,477 INFO    HandlerThread:8173 [handler.py:handle_request_defer():184] handle defer: 14
2024-10-06 21:26:53,477 DEBUG   SenderThread:8173 [sender.py:send():379] send: footer
2024-10-06 21:26:53,478 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:53,478 INFO    SenderThread:8173 [sender.py:send_request_defer():610] handle sender defer: 14
2024-10-06 21:26:53,479 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:26:53,479 DEBUG   SenderThread:8173 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:26:53,480 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:53,481 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: get_summary
2024-10-06 21:26:53,481 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: sampled_history
2024-10-06 21:26:53,483 DEBUG   HandlerThread:8173 [handler.py:handle_request():158] handle_request: shutdown
2024-10-06 21:26:53,483 INFO    HandlerThread:8173 [handler.py:finish():882] shutting down handler
2024-10-06 21:26:54,485 INFO    SenderThread:8173 [sender.py:finish():1608] shutting down sender
2024-10-06 21:26:54,485 INFO    WriterThread:8173 [datastore.py:close():296] close: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212628-m7n8eg77/run-m7n8eg77.wandb
2024-10-06 21:26:54,486 INFO    SenderThread:8173 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:26:54,486 INFO    SenderThread:8173 [file_pusher.py:join():175] waiting for file pusher
