2024-10-06 21:33:19,174 INFO    StreamThr :8388 [internal.py:wandb_internal():85] W&B internal server running at pid: 8388, started at: 2024-10-06 21:33:19.174257
2024-10-06 21:33:19,175 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: status
2024-10-06 21:33:19,176 INFO    WriterThread:8388 [datastore.py:open_for_write():87] open: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/run-wn33h0zr.wandb
2024-10-06 21:33:19,177 DEBUG   SenderThread:8388 [sender.py:send():379] send: header
2024-10-06 21:33:19,177 DEBUG   SenderThread:8388 [sender.py:send():379] send: run
2024-10-06 21:33:19,445 INFO    SenderThread:8388 [dir_watcher.py:__init__():211] watching files in: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files
2024-10-06 21:33:19,445 INFO    SenderThread:8388 [sender.py:_start_run_threads():1188] run started: wn33h0zr with start time 1728268399.175037
2024-10-06 21:33:19,452 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: check_version
2024-10-06 21:33:19,452 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: check_version
2024-10-06 21:33:19,508 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: run_start
2024-10-06 21:33:19,515 DEBUG   HandlerThread:8388 [system_info.py:__init__():26] System info init
2024-10-06 21:33:19,515 DEBUG   HandlerThread:8388 [system_info.py:__init__():41] System info init done
2024-10-06 21:33:19,516 INFO    HandlerThread:8388 [system_monitor.py:start():194] Starting system monitor
2024-10-06 21:33:19,516 INFO    SystemMonitor:8388 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-10-06 21:33:19,516 INFO    HandlerThread:8388 [system_monitor.py:probe():214] Collecting system info
2024-10-06 21:33:19,516 INFO    SystemMonitor:8388 [interfaces.py:start():188] Started cpu monitoring
2024-10-06 21:33:19,517 INFO    SystemMonitor:8388 [interfaces.py:start():188] Started disk monitoring
2024-10-06 21:33:19,520 INFO    SystemMonitor:8388 [interfaces.py:start():188] Started gpuapple monitoring
2024-10-06 21:33:19,520 ERROR   HandlerThread:8388 [gpu_apple.py:probe():176] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:33:19,522 INFO    SystemMonitor:8388 [interfaces.py:start():188] Started memory monitoring
2024-10-06 21:33:19,523 ERROR   gpuapple  :8388 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:33:19,525 DEBUG   HandlerThread:8388 [system_info.py:probe():152] Probing system
2024-10-06 21:33:19,526 INFO    SystemMonitor:8388 [interfaces.py:start():188] Started network monitoring
2024-10-06 21:33:19,528 DEBUG   HandlerThread:8388 [gitlib.py:_init_repo():56] git repository is invalid
2024-10-06 21:33:19,529 DEBUG   HandlerThread:8388 [system_info.py:probe():200] Probing system done
2024-10-06 21:33:19,529 DEBUG   HandlerThread:8388 [system_monitor.py:probe():223] {'os': 'macOS-14.6.1-arm64-arm-64bit', 'python': '3.12.2', 'heartbeatAt': '2024-10-07T02:33:19.526819', 'startedAt': '2024-10-07T02:33:19.168544', 'docker': None, 'cuda': None, 'args': ('data.pkl',), 'state': 'running', 'program': '/Users/milind/Desktop/valence/milind_code/non_llm.py', 'codePathLocal': 'non_llm.py', 'codePath': 'non_llm.py', 'host': 'Milinds-MacBook-Pro.local', 'username': 'milind', 'executable': '/opt/anaconda3/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 166.47719955444336}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-10-06 21:33:19,529 INFO    HandlerThread:8388 [system_monitor.py:probe():224] Finished collecting system info
2024-10-06 21:33:19,529 INFO    HandlerThread:8388 [system_monitor.py:probe():227] Publishing system info
2024-10-06 21:33:19,529 DEBUG   HandlerThread:8388 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-10-06 21:33:20,446 INFO    Thread-12 :8388 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/conda-environment.yaml
2024-10-06 21:33:21,534 ERROR   gpuapple  :8388 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:33:21,669 DEBUG   HandlerThread:8388 [system_info.py:_save_conda():224] Saving conda packages done
2024-10-06 21:33:21,670 INFO    HandlerThread:8388 [system_monitor.py:probe():229] Finished publishing system info
2024-10-06 21:33:21,672 DEBUG   SenderThread:8388 [sender.py:send():379] send: files
2024-10-06 21:33:21,672 INFO    SenderThread:8388 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-10-06 21:33:21,905 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: python_packages
2024-10-06 21:33:21,905 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: python_packages
2024-10-06 21:33:21,905 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 21:33:21,906 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: stop_status
2024-10-06 21:33:21,906 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:33:21,986 INFO    wandb-upload_0:8388 [upload_job.py:push():130] Uploaded file /var/folders/jv/wvjkll0d0vl_clbchr37hpk40000gn/T/tmpyznfjdvfwandb/y0ls16s1-wandb-metadata.json
2024-10-06 21:33:22,036 DEBUG   SenderThread:8388 [sender.py:send():379] send: telemetry
2024-10-06 21:33:22,460 INFO    Thread-12 :8388 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/conda-environment.yaml
2024-10-06 21:33:22,462 INFO    Thread-12 :8388 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/wandb-metadata.json
2024-10-06 21:33:22,464 INFO    Thread-12 :8388 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/requirements.txt
2024-10-06 21:33:22,464 INFO    Thread-12 :8388 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/output.log
2024-10-06 21:33:22,907 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:33:23,541 ERROR   gpuapple  :8388 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:33:23,910 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:33:24,470 INFO    Thread-12 :8388 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/output.log
2024-10-06 21:33:24,915 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:33:25,064 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:33:25,550 ERROR   gpuapple  :8388 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:33:25,942 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:33:26,942 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:33:27,589 ERROR   gpuapple  :8388 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:33:27,944 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:33:28,942 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:33:29,611 ERROR   gpuapple  :8388 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:33:29,942 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:33:30,933 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:33:30,945 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:33:31,624 ERROR   gpuapple  :8388 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:33:31,960 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:33:32,960 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:33:33,630 ERROR   gpuapple  :8388 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:33:33,963 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:33:34,967 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:33:35,026 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:33:35,026 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:33:35,027 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:33:35,027 DEBUG   SenderThread:8388 [sender.py:send():379] send: history
2024-10-06 21:33:35,027 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:33:35,027 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:33:35,028 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:33:35,029 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:33:35,029 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:33:35,029 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:33:35,029 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:33:35,029 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:33:35,029 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:33:35,030 INFO    SenderThread:8388 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:33:35,031 DEBUG   SenderThread:8388 [sender.py:send():379] send: history
2024-10-06 21:33:35,031 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:33:35,031 INFO    SenderThread:8388 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:33:35,031 DEBUG   SenderThread:8388 [sender.py:send():379] send: history
2024-10-06 21:33:35,031 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:33:35,031 INFO    SenderThread:8388 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:33:35,031 DEBUG   SenderThread:8388 [sender.py:send():379] send: history
2024-10-06 21:33:35,031 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:33:35,031 INFO    SenderThread:8388 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:33:35,031 DEBUG   SenderThread:8388 [sender.py:send():379] send: history
2024-10-06 21:33:35,032 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:33:35,032 INFO    SenderThread:8388 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:33:35,032 DEBUG   SenderThread:8388 [sender.py:send():379] send: history
2024-10-06 21:33:35,032 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:33:35,032 INFO    SenderThread:8388 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:33:35,032 DEBUG   SenderThread:8388 [sender.py:send():379] send: history
2024-10-06 21:33:35,032 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:33:35,032 INFO    SenderThread:8388 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:33:35,032 DEBUG   SenderThread:8388 [sender.py:send():379] send: history
2024-10-06 21:33:35,032 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:33:35,032 INFO    SenderThread:8388 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:33:35,032 DEBUG   SenderThread:8388 [sender.py:send():379] send: history
2024-10-06 21:33:35,032 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:33:35,032 INFO    SenderThread:8388 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:33:35,032 DEBUG   SenderThread:8388 [sender.py:send():379] send: history
2024-10-06 21:33:35,032 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:33:35,032 INFO    SenderThread:8388 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:33:35,033 DEBUG   SenderThread:8388 [sender.py:send():379] send: history
2024-10-06 21:33:35,033 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:33:35,033 INFO    SenderThread:8388 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:33:35,608 INFO    Thread-12 :8388 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/wandb-summary.json
2024-10-06 21:33:35,638 ERROR   gpuapple  :8388 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:33:35,734 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:33:35,735 DEBUG   SenderThread:8388 [sender.py:send():379] send: history
2024-10-06 21:33:35,735 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:33:35,735 INFO    SenderThread:8388 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:33:35,738 DEBUG   SenderThread:8388 [sender.py:send():379] send: telemetry
2024-10-06 21:33:35,744 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: server_info
2024-10-06 21:33:35,744 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: server_info
2024-10-06 21:33:35,789 DEBUG   SenderThread:8388 [sender.py:send():379] send: exit
2024-10-06 21:33:35,789 INFO    SenderThread:8388 [sender.py:send_exit():586] handling exit code: 0
2024-10-06 21:33:35,789 INFO    SenderThread:8388 [sender.py:send_exit():588] handling runtime: 16
2024-10-06 21:33:35,790 INFO    SenderThread:8388 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:33:35,790 INFO    SenderThread:8388 [sender.py:send_exit():594] send defer
2024-10-06 21:33:35,790 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:33:35,790 INFO    HandlerThread:8388 [handler.py:handle_request_defer():184] handle defer: 0
2024-10-06 21:33:35,790 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: defer
2024-10-06 21:33:35,790 INFO    SenderThread:8388 [sender.py:send_request_defer():610] handle sender defer: 0
2024-10-06 21:33:35,790 INFO    SenderThread:8388 [sender.py:transition_state():614] send defer: 1
2024-10-06 21:33:35,790 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:33:35,790 INFO    HandlerThread:8388 [handler.py:handle_request_defer():184] handle defer: 1
2024-10-06 21:33:35,790 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: defer
2024-10-06 21:33:35,790 INFO    SenderThread:8388 [sender.py:send_request_defer():610] handle sender defer: 1
2024-10-06 21:33:35,790 INFO    SenderThread:8388 [sender.py:transition_state():614] send defer: 2
2024-10-06 21:33:35,790 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:33:35,790 INFO    HandlerThread:8388 [handler.py:handle_request_defer():184] handle defer: 2
2024-10-06 21:33:35,790 INFO    HandlerThread:8388 [system_monitor.py:finish():203] Stopping system monitor
2024-10-06 21:33:35,790 DEBUG   SystemMonitor:8388 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-10-06 21:33:35,790 DEBUG   SystemMonitor:8388 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-10-06 21:33:35,790 DEBUG   SystemMonitor:8388 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-10-06 21:33:35,791 INFO    HandlerThread:8388 [interfaces.py:finish():200] Joined cpu monitor
2024-10-06 21:33:35,791 INFO    HandlerThread:8388 [interfaces.py:finish():200] Joined disk monitor
2024-10-06 21:33:35,791 INFO    HandlerThread:8388 [interfaces.py:finish():200] Joined gpuapple monitor
2024-10-06 21:33:35,791 INFO    HandlerThread:8388 [interfaces.py:finish():200] Joined memory monitor
2024-10-06 21:33:35,791 INFO    HandlerThread:8388 [interfaces.py:finish():200] Joined network monitor
2024-10-06 21:33:35,791 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: defer
2024-10-06 21:33:35,791 INFO    SenderThread:8388 [sender.py:send_request_defer():610] handle sender defer: 2
2024-10-06 21:33:35,791 INFO    SenderThread:8388 [sender.py:transition_state():614] send defer: 3
2024-10-06 21:33:35,791 DEBUG   SenderThread:8388 [sender.py:send():379] send: telemetry
2024-10-06 21:33:35,791 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:33:35,791 INFO    HandlerThread:8388 [handler.py:handle_request_defer():184] handle defer: 3
2024-10-06 21:33:35,791 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: defer
2024-10-06 21:33:35,791 INFO    SenderThread:8388 [sender.py:send_request_defer():610] handle sender defer: 3
2024-10-06 21:33:35,791 INFO    SenderThread:8388 [sender.py:transition_state():614] send defer: 4
2024-10-06 21:33:35,791 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:33:35,791 INFO    HandlerThread:8388 [handler.py:handle_request_defer():184] handle defer: 4
2024-10-06 21:33:35,791 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: defer
2024-10-06 21:33:35,791 INFO    SenderThread:8388 [sender.py:send_request_defer():610] handle sender defer: 4
2024-10-06 21:33:35,791 INFO    SenderThread:8388 [sender.py:transition_state():614] send defer: 5
2024-10-06 21:33:35,791 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:33:35,791 INFO    HandlerThread:8388 [handler.py:handle_request_defer():184] handle defer: 5
2024-10-06 21:33:35,791 DEBUG   SenderThread:8388 [sender.py:send():379] send: summary
2024-10-06 21:33:35,792 INFO    SenderThread:8388 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:33:35,792 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: defer
2024-10-06 21:33:35,792 INFO    SenderThread:8388 [sender.py:send_request_defer():610] handle sender defer: 5
2024-10-06 21:33:35,792 INFO    SenderThread:8388 [sender.py:transition_state():614] send defer: 6
2024-10-06 21:33:35,792 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:33:35,792 INFO    HandlerThread:8388 [handler.py:handle_request_defer():184] handle defer: 6
2024-10-06 21:33:35,792 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: defer
2024-10-06 21:33:35,792 INFO    SenderThread:8388 [sender.py:send_request_defer():610] handle sender defer: 6
2024-10-06 21:33:35,793 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:33:35,935 INFO    SenderThread:8388 [sender.py:transition_state():614] send defer: 7
2024-10-06 21:33:35,935 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:33:35,935 INFO    HandlerThread:8388 [handler.py:handle_request_defer():184] handle defer: 7
2024-10-06 21:33:35,935 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: defer
2024-10-06 21:33:35,935 INFO    SenderThread:8388 [sender.py:send_request_defer():610] handle sender defer: 7
2024-10-06 21:33:36,614 INFO    Thread-12 :8388 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/config.yaml
2024-10-06 21:33:36,615 INFO    Thread-12 :8388 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/wandb-summary.json
2024-10-06 21:33:36,615 INFO    Thread-12 :8388 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/output.log
2024-10-06 21:33:36,793 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:33:38,123 INFO    SenderThread:8388 [sender.py:transition_state():614] send defer: 8
2024-10-06 21:33:38,123 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:33:38,124 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:33:38,125 INFO    HandlerThread:8388 [handler.py:handle_request_defer():184] handle defer: 8
2024-10-06 21:33:38,125 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: defer
2024-10-06 21:33:38,126 INFO    SenderThread:8388 [sender.py:send_request_defer():610] handle sender defer: 8
2024-10-06 21:33:38,126 INFO    SenderThread:8388 [job_builder.py:build():440] Attempting to build job artifact
2024-10-06 21:33:38,127 INFO    SenderThread:8388 [job_builder.py:_get_source_type():580] no source found
2024-10-06 21:33:38,127 INFO    SenderThread:8388 [sender.py:transition_state():614] send defer: 9
2024-10-06 21:33:38,127 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:33:38,127 INFO    HandlerThread:8388 [handler.py:handle_request_defer():184] handle defer: 9
2024-10-06 21:33:38,127 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: defer
2024-10-06 21:33:38,127 INFO    SenderThread:8388 [sender.py:send_request_defer():610] handle sender defer: 9
2024-10-06 21:33:38,127 INFO    SenderThread:8388 [dir_watcher.py:finish():358] shutting down directory watcher
2024-10-06 21:33:38,618 INFO    Thread-12 :8388 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/output.log
2024-10-06 21:33:38,619 INFO    SenderThread:8388 [dir_watcher.py:finish():388] scan: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files
2024-10-06 21:33:38,619 INFO    SenderThread:8388 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/requirements.txt requirements.txt
2024-10-06 21:33:38,619 INFO    SenderThread:8388 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/output.log output.log
2024-10-06 21:33:38,626 INFO    SenderThread:8388 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/config.yaml config.yaml
2024-10-06 21:33:38,628 INFO    SenderThread:8388 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/wandb-summary.json wandb-summary.json
2024-10-06 21:33:38,628 INFO    SenderThread:8388 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/conda-environment.yaml conda-environment.yaml
2024-10-06 21:33:38,632 INFO    SenderThread:8388 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/wandb-metadata.json wandb-metadata.json
2024-10-06 21:33:38,633 INFO    SenderThread:8388 [sender.py:transition_state():614] send defer: 10
2024-10-06 21:33:38,633 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:33:38,633 INFO    HandlerThread:8388 [handler.py:handle_request_defer():184] handle defer: 10
2024-10-06 21:33:38,636 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: defer
2024-10-06 21:33:38,636 INFO    SenderThread:8388 [sender.py:send_request_defer():610] handle sender defer: 10
2024-10-06 21:33:38,636 INFO    SenderThread:8388 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:33:38,799 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:33:38,800 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:33:38,828 INFO    wandb-upload_0:8388 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/requirements.txt
2024-10-06 21:33:38,865 INFO    wandb-upload_4:8388 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/conda-environment.yaml
2024-10-06 21:33:38,878 INFO    wandb-upload_3:8388 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/wandb-summary.json
2024-10-06 21:33:38,879 INFO    wandb-upload_2:8388 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/config.yaml
2024-10-06 21:33:38,926 INFO    wandb-upload_1:8388 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/files/output.log
2024-10-06 21:33:39,131 INFO    Thread-11 (_thread_body):8388 [sender.py:transition_state():614] send defer: 11
2024-10-06 21:33:39,134 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:33:39,135 INFO    HandlerThread:8388 [handler.py:handle_request_defer():184] handle defer: 11
2024-10-06 21:33:39,136 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: defer
2024-10-06 21:33:39,136 INFO    SenderThread:8388 [sender.py:send_request_defer():610] handle sender defer: 11
2024-10-06 21:33:39,136 INFO    SenderThread:8388 [file_pusher.py:join():175] waiting for file pusher
2024-10-06 21:33:39,137 INFO    SenderThread:8388 [sender.py:transition_state():614] send defer: 12
2024-10-06 21:33:39,137 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:33:39,137 INFO    HandlerThread:8388 [handler.py:handle_request_defer():184] handle defer: 12
2024-10-06 21:33:39,137 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: defer
2024-10-06 21:33:39,137 INFO    SenderThread:8388 [sender.py:send_request_defer():610] handle sender defer: 12
2024-10-06 21:33:39,137 INFO    SenderThread:8388 [file_stream.py:finish():601] file stream finish called
2024-10-06 21:33:39,393 INFO    SenderThread:8388 [file_stream.py:finish():605] file stream finish is done
2024-10-06 21:33:39,393 INFO    SenderThread:8388 [sender.py:transition_state():614] send defer: 13
2024-10-06 21:33:39,394 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:33:39,394 INFO    HandlerThread:8388 [handler.py:handle_request_defer():184] handle defer: 13
2024-10-06 21:33:39,394 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: defer
2024-10-06 21:33:39,394 INFO    SenderThread:8388 [sender.py:send_request_defer():610] handle sender defer: 13
2024-10-06 21:33:39,394 INFO    SenderThread:8388 [sender.py:transition_state():614] send defer: 14
2024-10-06 21:33:39,395 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:33:39,395 DEBUG   SenderThread:8388 [sender.py:send():379] send: final
2024-10-06 21:33:39,395 INFO    HandlerThread:8388 [handler.py:handle_request_defer():184] handle defer: 14
2024-10-06 21:33:39,395 DEBUG   SenderThread:8388 [sender.py:send():379] send: footer
2024-10-06 21:33:39,395 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: defer
2024-10-06 21:33:39,395 INFO    SenderThread:8388 [sender.py:send_request_defer():610] handle sender defer: 14
2024-10-06 21:33:39,397 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:33:39,397 DEBUG   SenderThread:8388 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:33:39,400 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:33:39,401 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: get_summary
2024-10-06 21:33:39,401 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: sampled_history
2024-10-06 21:33:39,404 DEBUG   HandlerThread:8388 [handler.py:handle_request():158] handle_request: shutdown
2024-10-06 21:33:39,405 INFO    HandlerThread:8388 [handler.py:finish():882] shutting down handler
2024-10-06 21:33:40,398 INFO    WriterThread:8388 [datastore.py:close():296] close: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213319-wn33h0zr/run-wn33h0zr.wandb
2024-10-06 21:33:40,403 INFO    SenderThread:8388 [sender.py:finish():1608] shutting down sender
2024-10-06 21:33:40,403 INFO    SenderThread:8388 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:33:40,403 INFO    SenderThread:8388 [file_pusher.py:join():175] waiting for file pusher
